In [2]:
# import python packages
import numpy as np
from numpy.linalg import norm

import random
from math import sqrt

# set random seed
randomSeed = 12345678

def randomUnitVector(n):
    unnormalized = [random.normalvariate(0, 
      1) for _ in range(n)]
    xNorm = sqrt(sum(x * x for x in unnormalized))
    return [x / xNorm for x in unnormalized]

def svdPowerMethod_1d(A, epsilon=1e-10):
    m, n = A.shape
    x = randomUnitVector(min(m,n))
    lastV = None
    V = x
    if m > n:
        B = np.dot(A.T, A)
    else:
        B = np.dot(A, A.T)
    while True:
        lastV = V
        print('B')
        print(B)
        V = np.dot(B, lastV)
        V = V / norm(V)
        print('V')
        print(V)
        if abs(np.dot(V, lastV)) > 1 - epsilon:
            return V

def svdPowerMethodRow(A, k=None, epsilon=1e-10):
    A = np.array(A, dtype=float)
    m, n = A.shape
    svdEstimate = []
    if k is None:
        k = min(m, n)
    for i in range(k):
        matrixFor1D = A.copy()
        for singularValue, u, v in svdEstimate[:i]:
            matrixFor1D -= singularValue * np.outer(u, v)
        v = svdPowerMethod_1d(matrixFor1D,epsilon=epsilon)
        u_unnormalized = np.dot(A, v)
        sigma = norm(u_unnormalized)
        u = u_unnormalized / sigma
        svdEstimate.append((sigma, u, v))
    output = [np.array(x) for x in zip(*svdEstimate)]
    singularValues, us, vs = output
    return singularValues, us.T, vs

def svdPowerMethodColumn(A, k=None, epsilon=1e-10):
    A = np.array(A, dtype=float)
    m, n = A.shape
    svdEstimate = []
    if k is None:
        k = min(m, n)
    for i in range(k):
        matrixFor1D = A.copy()
        for singularValue, u, v in svdEstimate[:i]:
            matrixFor1D -= singularValue * np.outer(u, v)
        u = svdPowerMethod_1d(matrixFor1D,epsilon=epsilon)
        v_unnormalized = np.dot(A.T, u)
        sigma = norm(v_unnormalized)
        v = v_unnormalized / sigma
        svdEstimate.append((sigma, u, v))
    output = [np.array(x) for x in zip(*svdEstimate)]
    singularValues, us, vs = output
    return singularValues, us.T, vs

def svdPowerMethod(A, k=None, epsilon=1e-10):
    A = np.array(A, dtype=float)
    m, n = A.shape
    if m > n:
      s, uT, vs=svdPowerMethodRow(A,
      k, epsilon=1e-10)
    else:
      s, uT, vs=svdPowerMethodColumn(A, 
      k, epsilon=1e-10)
    return s, uT, vs






In [3]:
random.seed(randomSeed)
np.random.seed(randomSeed)

# create sample matrix
A = np.array([
  [4, 1, 1],
  [2, 5, 3],
  [1, 2, 1],
  [4, 5, 5],
  [3, 5, 2],
  [2, 4, 2],  
  [5, 3, 1],
  [2, 2, 5],
  ], dtype='float64')

# determine n rows and m columns
m,n = A.shape
print("A is a "+str(m)+", x "+str(n)+" matrix")

A is a 8, x 3 matrix


In [24]:
matrixFor1D = A.copy()
matrixFor1D -= A

In [25]:
print(matrixFor1D)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [26]:
B = np.dot(A.T,A)

In [27]:
print(B)

[[ 79.  78.  56.]
 [ 78. 109.  74.]
 [ 56.  74.  70.]]


In [12]:
v1=svdPowerMethod_1d(A, epsilon=1e-10)

B
[[ 79.  78.  56.]
 [ 78. 109.  74.]
 [ 56.  74.  70.]]
V
[-0.99954365  0.00198764  0.03014217]
B
[[ 79.  78.  56.]
 [ 78. 109.  74.]
 [ 56.  74.  70.]]
V
[-0.6396599  -0.62635826 -0.44554522]
B
[[ 79.  78.  56.]
 [ 78. 109.  74.]
 [ 56.  74.  70.]]
V
[-0.54976049 -0.66824305 -0.50121315]
B
[[ 79.  78.  56.]
 [ 78. 109.  74.]
 [ 56.  74.  70.]]
V
[-0.54247194 -0.67055159 -0.50604818]
B
[[ 79.  78.  56.]
 [ 78. 109.  74.]
 [ 56.  74.  70.]]
V
[-0.54189769 -0.67069912 -0.50646775]
B
[[ 79.  78.  56.]
 [ 78. 109.  74.]
 [ 56.  74.  70.]]
V
[-0.54185205 -0.67070917 -0.50650327]
B
[[ 79.  78.  56.]
 [ 78. 109.  74.]
 [ 56.  74.  70.]]
V
[-0.5418484  -0.67070989 -0.50650622]


In [4]:
# compute SVD
singularValues,U,V = svdPowerMethod(A)


B
[[ 79.  78.  56.]
 [ 78. 109.  74.]
 [ 56.  74.  70.]]
V
[0.68045772 0.53348207 0.50236855]
B
[[ 79.  78.  56.]
 [ 78. 109.  74.]
 [ 56.  74.  70.]]
V
[0.55238005 0.66375078 0.50429275]
B
[[ 79.  78.  56.]
 [ 78. 109.  74.]
 [ 56.  74.  70.]]
V
[0.54261749 0.6703221  0.50619616]
B
[[ 79.  78.  56.]
 [ 78. 109.  74.]
 [ 56.  74.  70.]]
V
[0.54190602 0.67068729 0.5064745 ]
B
[[ 79.  78.  56.]
 [ 78. 109.  74.]
 [ 56.  74.  70.]]
V
[0.54185255 0.67070856 0.50650355]
B
[[ 79.  78.  56.]
 [ 78. 109.  74.]
 [ 56.  74.  70.]]
V
[0.54184843 0.67070986 0.50650623]
B
[[12.08948316 -4.82311618 -6.54632798]
 [-4.82311618  6.47996431 -3.42103983]
 [-6.54632798 -3.42103983 11.53320989]]
V
[-0.81855263  0.55786899  0.13694447]
B
[[12.08948316 -4.82311618 -6.54632798]
 [-4.82311618  6.47996431 -3.42103983]
 [-6.54632798 -3.42103983 11.53320989]]
V
[-0.84036426  0.44217994  0.31347218]
B
[[12.08948316 -4.82311618 -6.54632798]
 [-4.82311618  6.47996431 -3.42103983]
 [-6.54632798 -3.42103983 11.5332098

In [5]:
rS,cS=np.diag(singularValues).shape
rU,cU=U.shape
rV,cV=V.shape

In [6]:
print(U)

[[ 0.22155208 -0.52086662 -0.39333697]
 [ 0.39458523  0.23924155  0.35445363]
 [ 0.15830232  0.03055162  0.15299691]
 [ 0.53347447  0.19168664 -0.19949776]
 [ 0.39692635 -0.08648347  0.41053093]
 [ 0.31660463  0.06110323  0.30599382]
 [ 0.34630265 -0.64128879 -0.07381356]
 [ 0.32840218  0.45969551 -0.62355828]]


In [22]:
np.round(np.dot(U.T,U),2)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
np.round(np.dot(V,V.T),2)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [7]:
print(np.diag(singularValues))

[[15.09626916  0.          0.        ]
 [ 0.          4.30056855  0.        ]
 [ 0.          0.          3.40701739]]


In [8]:
print(V)

[[ 0.54184843  0.67070986  0.50650623]
 [-0.75152966  0.11682294  0.6492731 ]
 [-0.37630233  0.73246207 -0.56735868]]


In [9]:
# reconstitute matrix A
Sigma = np.diag(singularValues)
# reconstitute matrix A
AA=np.dot(U, np.dot(Sigma, V))

In [28]:
print(np.dot(Sigma, V))

[[ 8.17988977 10.12521654  7.64635442]
 [-3.23200484  0.50240505  2.7922435 ]
 [-1.28206857  2.49551102 -1.93300089]]


In [10]:
print(AA)

[[4. 1. 1.]
 [2. 5. 3.]
 [1. 2. 1.]
 [4. 5. 5.]
 [3. 5. 2.]
 [2. 4. 2.]
 [5. 3. 1.]
 [2. 2. 5.]]


In [11]:
# define number of digits for rounding
nDigits=10

print(np.round(A - AA, decimals=nDigits))


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
